name: Monitor PHP 8.2

on:
  schedule:
    - cron: "0 6 * * *"
  repository_dispatch:
    types:
      - monitor-php8.2

jobs:
  test_extensions:
    strategy:
      fail-fast: false
      matrix:
        distro:
          - alpine3.15
          - alpine3.16
          - alpine3.17
          - alpine3.18
          - buster
          - bullseye
          - bookworm
    name: Check on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    env:
      IPETEST_DOCKER_DISTRO: ${{ matrix.distro }}
      IPETEST_ONLY_PHPVERSIONS: "8.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test extensions
        run: ./scripts/ci-test-extensions all
      - name: Notify failures
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          message: Testing packages against PHP 8.2 failed on https://github.com/mlocati/docker-php-extension-installer
