name: Monitor PHP 8.5

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test_extensions:
    strategy:
      fail-fast: false
      matrix:
        distro:
          - alpine3.21
          - alpine3.22
          - alpine3.23
          - bullseye
          - bookworm
          - trixie
    name: Check on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    env:
      IPETEST_DOCKER_DISTRO: ${{ matrix.distro }}
      IPETEST_ONLY_PHPVERSIONS: "8.5"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test extensions
        run: ./scripts/ci-test-extensions all
      - name: Notify failures
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          message: Testing packages against PHP 8.5 failed on https://github.com/mlocati/docker-php-extension-installer/actions/workflows/monitor-php8.5.yml
